### ISSUE TITLE
How to disable a Softr button of a CTA (no action set up) + Correctly get this button to run a JS snippet

### ISSUE THREAD

**Issue by git-matthieu** [dcoletta/scissors#1]
First issue creation attempt. To be improved.

Let's go straight to the point. Everything explained here, but read what's below too, as I think my issue is beyond this specific use case.
[Demo](https://test-play.softr.app/artur-s-test-page) 

Many of us (Softr users) would like to use the Softr buttons to run JS codes. I really think solving this would be a very good base for Softr users trying to enter the low-code space. After all, button are here to run actions 🤷‍♀️.

We had a chat together and we found a way to make it happen (copy pasting the outer HTML). 
**I would like something more... general, industrial I would say.**

I tried multiple times, for example, to use a query selector... My problem is that I'm incapable of determining what would be the right query selector for a Softr button. Impossible to find, for example a button id, that would simplify everything.

**Comment by dcoletta** [comment]
You're right - as far as I know you can't use `document.querySelector()`, at least not that I know of.

It can be done with jQuery pretty easily, but I prefer not to use jQuery when there's another way. 

Fortunately, there is:
```
// say you have a button whose label is "See All Videos"
// this is going to show up in the page as an anchor tag
var iterator = document.evaluate("//a[contains(., 'See All Videos')]", document);
var btn = iterator.iterateNext();
```

**Comment by git-matthieu** [comment]
Did it!!

Here is the snippet, using your method, to create a tabs feature within Softr (Here, one CTA block with only three buttons where the texts "Button list 1", "Button list 2", "Button list 3" are written for the corresponding button. Each of the three buttons makes appear one different Softr block. In this case, these are static blocks, but it works perfectly with dynamic too. The ID of these blocks are "pricing1", "feature1" and "testimonial1".

`<script>
    window.addEventListener('DOMContentLoaded', (event) => {
        document.getElementById("pricing1").style.display = "block";
        document.getElementById("feature1").style.display = "none";
        document.getElementById("testimonial1").style.display = "none"
    });

    window.addEventListener('block-loaded-cta1', () => {
        console.log('CTA Block loaded');

        const buttonClickHandler = (e) => {
            var iterator = document.evaluate("//a[contains(., 'Button list 1')]", document);
            var btn = iterator.iterateNext();

            if (e.target === btn || e.target.parentNode === btn) {
                console.log('Click Button 1');
                document.getElementById("pricing1").style.display = "block";
                document.getElementById("feature1").style.display = "none";
                document.getElementById("testimonial1").style.display = "none";
            }

            iterator = document.evaluate("//a[contains(., 'Button list 2')]", document);
            btn = iterator.iterateNext();
            if (e.target === btn || e.target.parentNode === btn) {
                console.log('Click Button 2');
                document.getElementById("feature1").style.display = "block";
                document.getElementById("pricing1").style.display = "none";
                document.getElementById("testimonial1").style.display = "none";
            }

            iterator = document.evaluate("//a[contains(., 'Button list 3')]", document);
            btn = iterator.iterateNext();
            if (e.target === btn || e.target.parentNode === btn) {
                console.log('Click Button 3');
                document.getElementById("testimonial1").style.display = "block";
                document.getElementById("pricing1").style.display = "none";
                document.getElementById("feature1").style.display = "none";
            }
        };

        document.body.addEventListener('click', buttonClickHandler);
    });
</script>`

**Comment by git-matthieu** [comment]
My main problem was to add this part: `e.target.parentnode === btn`
Had to dig in a long time in stackoverflow to find the right syntax, adapted to this snippet.

Without parentnode the behaviour was stange: blocks were shown only if I clicked on the right button but outside of the text.
